settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2024-04-11T16:05:12.177 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: -6869.98377088077 km
      pos_y: 670.4256883056528 km
      pos_z: -0.014697186479523049 km
      vel_x: 0.16347930550455203 km/s
      vel_y: 1.4802787927199006 km/s
      vel_z: 7.539235643405847 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2024-04-12T16:05:12.177 TDB
  type: point
