settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2025-04-28T16:58:48.719 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: 1436.8389865663971 km
      pos_y: 6936.36948707324 km
      pos_z: -0.004872499213381374 km
      vel_x: 1.5501302121490426 km/s
      vel_y: -0.32999029841903393 km/s
      vel_z: 7.426658281588236 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2025-04-29T16:58:48.719 TDB
  type: point
