settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2024-12-31T12:00:00.000 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: 3658.0020964197256 km
      pos_y: -5724.093875812191 km
      pos_z: -0.012407939625936566 km
      vel_x: 3.586143230226753 km/s
      vel_y: 2.298486941842384 km/s
      vel_z: 6.010862198856115 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2025-01-01T12:00:00.000 TDB
  type: point
