settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2025-05-16T20:42:21.200 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: 810.9400756539379 km
      pos_y: -6749.061684368199 km
      pos_z: -0.020247219977091332 km
      vel_x: 4.225398824916624 km/s
      vel_y: 0.515905139654933 km/s
      vel_z: 6.007976118827507 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2025-05-17T20:42:21.200 TDB
  type: point
