# Trajectory File

settings:
  steps: 10000000 # 100000 default value for the maximum number of steps the propagator will be allowed  to take
  stepper: 
    method: adams # numerical integration stepper method to use during propagation, MUST BE ONE OF: "rk787", "rk788", "adams"
  initialStep: 10 s # default value  for the initial step size of the propagator in each segment (control) point
  relTol: 1e-09 # default value for the numerical relative error tolerance for the propagator
  absTol: 1e-09 # default value for the numerical absolute error tolerance for the propagator
  #options: ... # additional options passed to the numerical integrator stepper
  timeScale: TDB # default time scale of the propagation, MUST BE ONE OF: "TCB", "TDB", "TT", "TCG", "TAI", "UT1", "GPS"

setup:
  - name: SC # name of the propagated quantity
    type: group # type of propagated quantity, MUST BE ONE OF: "point", "axes", "scalar", "vector", "group"
    spacecraft: SC
    input:
    - name: center
      type: point
    # - name: mass
    #   type: scalar
    #   unit: kg
    # - name: dv
    #   type: scalar
    #   unit: m/s
  #axes: ICRF # default axes of propagation for this point quantity
  #dimension: ... # dimension of the propagated vector quantity
  #unit: ... # unit requrement for checking input values, default "", Example: "m/s", "s", "J"
  #relTol: 1e-09 # default value for the numerical relative error tolerance for the quantity
  #absTol: 1e-09 # default value for the numerical absolute error tolerance for the quantity

timeline:
  - type: control
    name: start
    epoch: 2021-10-23T19:24:00 TDB
    state: # initial state model definition for propagated quantities 
      - name: SC_center # name of the quantity to set initial model for
        body: Earth # central body used for both initial state and initial center of integration for propagated points. If body is given, point and coi shall not be. 
        #point: NO
        #coi: NO
        axes: ITRF # axes of the initial state for propagated points
        dynamics: EMS_combined # dynamic model for the propagation of the quantity
        value: # using state vector for STELLA
          pos_x: 6876.5701861 km
          pos_y: -1975.00094305 km
          pos_z: -660.03339253 km
          vel_x: 0.17227756 km/s
          vel_y: -1.80596358 km/s
          vel_z: 7.32616064 km/s
          
  - type: point
    name: end
    input: SC
    point:
      epoch: 2021-10-24T19:24:00 TDB