settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2024-12-31T00:00:00.000 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: -3707.1014736717852 km
      pos_y: 5692.418528126639 km
      pos_z: 0.009749383515113036 km
      vel_x: -3.56623201869661 km/s
      vel_y: -2.329265261252658 km/s
      vel_z: 6.010860370513529 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2025-01-01T00:00:00.000 TDB
  type: point
