settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2023-06-07T20:53:20.443 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: -3652.845984102652 km
      pos_y: 5681.158931179815 km
      pos_z: 0.013465175878565954 km
      vel_x: -4.318277465333722 km/s
      vel_y: -2.763951255048596 km/s
      vel_z: 5.245493245049466 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2023-06-08T20:53:20.443 TDB
  type: point
