settings:
  absTol: 1.0e-09
  initialStep: 10 s
  relTol: 1.0e-09
  stepper:
    method: adams
  steps: 100000
  timeScale: TDB
setup:
- input:
  - name: center
    type: point
  name: SC
  spacecraft: SC
  type: group
timeline:
- epoch: 2024-12-31T03:39:41.750 TDB
  name: start
  state:
  - axes: ITRF
    body: Earth
    dynamics: EMS_combined
    name: SC_center
    value:
      pos_x: 2544.823570123811 km
      pos_y: 6298.420677169409 km
      pos_z: 0.006704120219376561 km
      vel_x: -3.9514601332211896 km/s
      vel_y: 1.5904016167978625 km/s
      vel_z: 6.0108664419829285 km/s
  type: control
- input: SC
  name: end
  point:
    epoch: 2025-01-01T03:39:41.750 TDB
  type: point
