# Universe File: Universe environment definition for computation and modelling

#! version
version: '3.0'
#! version

# #! stations
# stations:
#   # Create station database for Earth ground stations
#   - name: earth_stations
#     file: data/stations/GroundStationsDatabase.json
# #! stations

#! constants
constants:
  # Load constants from ephemeris, with optional additional mapping between names
  ephemeris:
    - source: gm431 # Ephemeris source object to load constants from
      mapping: spiceConstMap # Optional mapping for loaded ephemeris objects
  # Add user defined data: always specified in SI (km, kg, s)
  data:
    EarthGM: 398600.4415 # Override default Earth GM
    MoonGM: 4902.8029535968 # Override default Moon GM
#! constants

#! bodies
bodies:
  # Earth as body with Earth as the center of the body from the frames plugin
  - name: Earth
    point: Earth
    # Add non-spherical gravity field from file, attached to body-fixed axes ITRF
    gravity: # Gravitational parameter of the body
      - EarthGrav
    gm: EarthGrav
  - name: Sun
    point: Sun
  # Define Moon as point mass
  - name: Moon
    point: Moon
#! bodies

#! parameters
parameters:
  - name: mass
    type: Parameter
    value: 48 kg 
  - name: SC_cd
    type: Parameter
    value: '2.0'
  - name: SC_cr
    type: Parameter
    value: '1.131'
#! parameters

#! spacetime
spacetime: 
  system: BCRS # Default relativistic system name, MUST BE ONE OF: "BCRS", "GCRS"
#! spacetime

#! sphericalHarmonics
sphericalHarmonics:
  - name: EarthGrav
    type: File
    config:
      point: Earth
      degree: 32
      order: 32
      axes: ITRF
      file: data/gravity/eigen05c_80_sha.tab
#! sphericalHarmonics

#! ephemeris
ephemeris:
  # Named ephemeris objects with files to load
  - name: de432 #de405
    files:
      - data/ephemeris/unxp2000.405 #data/ephemeris/de432.jpl
    cache: false # Do not load file to memory
  # Another ephemeris for constants, default is loading file contents to memory
  - name: gm431
    files:
      - data/ephemeris/gm_de431.tpc
#! ephemeris

#! spacecraft
spacecraft:
 # Configuration for STELLA spacecraft
  - name: SC
    mass: 48 kg 
    # Solar radiation modelling surface properties
    srp:
      area: 0.05 m^2 
      cr: 1.131 # Reflectivity coefficient
    # Drag modelling surface properties
    drag:
      area: 0.05 m^2 
      cd: 2.0 # Drag coefficient
#! spacecraft

#! atmosphere
atmosphere:
  - name: EarthAtmos
    type: nrlmsise00 # Specific model for Earth
    config:
      point: Earth
      axes: ITRF # Atmosphere glued to Earth body-fixed frame
      file: data/atmosphere/solmag.ipf # Use solar activity file
#! atmosphere

#! mappings
mappings: # Various mapping definition to be used for associations
  # Map spice ephemeris constant to constant book
  - name: spiceConstMap
    data:
      BODY399_GM: EarthGM
#! mappings

#! lightTime
lightTime: # Light time definition
  - name: solarSystem
    bodies:
      - Sun
      - Earth
      - Moon
    refCenter: SSB
    refAxes: ICRF
#! lightTime

#! frames
frames:
  - name: ephemeris
    type: Ephem # Configuration for Ephem points in frames plugin
    config:
      source: de432 # de405
    #  mapping: interplanetary   # Custom (additional) mapping supplied
    # We can also add ipf files, with optional mapping
  - name: ITRF
    type: AxesOrient
    config:
      model: IERS2000   # Earth body fixed model
      nutation: data/orientation/nutation2000A.ipf   # Supply nutation interpolation file
      #erp: ''   # Use no pole correction
  # - name: stations
  #   type: Stations
  #   config: 
  #     source: earth_stations
#! frames

#! dynamics
dynamics: # Dynamic models for orbit propagation
  - name: EMS_gravity
    type: SystemGravity
    config:
      model: EMS
      axes: ICRF
      coi: Earth

  - name: EMS_srp
    type: SimpleSRP 
    config:
      mass: SC_mass
      area: SC_srp_area
      cr: SC_srp_cr
      occulters:
        - Earth
        - Moon
      axes: ICRF

  - name: EMS_drag
    type: SimpleDrag
    config:
      atmosphere: EarthAtmos
      mass: SC_mass
      area: SC_drag_area
      cd: SC_drag_cd

  - name: EMS_combined
    type: Combined
    config:
      - EMS_gravity
      - EMS_srp
      - EMS_drag
#! dynamics

#! gravity
gravity:
  # Earth, Moon and Sun system gravity
  - name: EMS
    bodies:
      - Sun 
      - Earth
      - Moon
#! gravity